// LOCALHOST
###
GET http://localhost:8080/trainers
###
GET http://localhost:8080/trainers/646faa55e0dbf9f86b44bce3
###
GET http://localhost:8080/trainers/646fab86e0dbf9f86b44bce4
###
GET http://localhost:8080/trainers/646fac2de0dbf9f86b44bce5

// PRODUCTION Deploy
###
GET https://week5-8.onrender.com/trainers

### 
GET https://week5-8.onrender.com/trainers/646faa55e0dbf9f86b44bce3

### 
GET https://week5-8.onrender.com/trainers/646fab86e0dbf9f86b44bce4

### 
GET https://week5-8.onrender.com/trainers/646fac2de0dbf9f86b44bce5

///
///Lesson 3
///

// LOCALHOST
### Get all contacts
GET http://localhost:8080/trainers

### Get contact by id
GET http://localhost:8080/trainers/646fac2de0dbf9f86b44bce5

### Create contact
POST http://localhost:8080/trainers HTTP/1.1
content-type: application/json
{
    "username":"D@wn10",
    "password":"c00rdin@tor",
    "displayName":"Dawn",
    "info": {
        "region": "Sinnoh",
        "pokemon": "Piplup",
        "type": "Water"
    }
}

### PUT contact
PUT http://localhost:8080/contacts/6453de61560c75d5af8daa7d HTTP/1.1
content-type: application/json
{
    "username":"letsGoh",
    "password":"futur3re@lity",
    "displayName":"Goh",
    "info": {
        "region": "Kanto",
        "pokemon": "Scorbunny",
        "type": "Fire"
    }
}

### DELETE contact
DELETE http://localhost:8080/contacts/64556d79505fb7dc0840ca7b HTTP/1.1

// PRODUCTION Deploy
### Get all contacts
GET https://week5-8.onrender.com/trainers


### Get contact by id
GET https://week5-8.onrender.com/contacts/6453de61560c75d5af8daa7d


### Create contact
POST https://week5-8.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Ashley",
    "lastName":"Weaver",
    "email":"aWeaver@test.com",
    "favoriteColor":"Brown",
    "birthday":"06/19/2000"
}


### PUT contact
PUT https://week5-8.onrender.com/contacts/6453de61560c75d5af8daa7d HTTP/1.1
content-type: application/json

{
    "firstName":"Krissie",
    "lastName":"Jones",
    "email":"kJones@test.com",
    "favoriteColor":"Black",
    "birthday":"01/26/94"
}


### DELETE contact
DELETE https://week5-8.onrender.com/contacts/64556dbd92456e69163719cd HTTP/1.1