// LOCALHOST
###
GET http://localhost:8080/trainers
###
GET http://localhost:8080/trainers/AKetchum
###
GET http://localhost:8080/trainers/CeruleanGymLeader
###
GET http://localhost:8080/trainers/letsGoh

### 
GET http://localhost:8080/regions/Kanto

// PRODUCTION Deploy
###
GET https://week5-8.onrender.com/trainers

### 
GET https://week5-8.onrender.com/trainers/AKetchum

### 
GET https://week5-8.onrender.com/regions/Kanto

### 
GET https://week5-8.onrender.com/trainers/CeruleanGymLeader

### 
GET https://week5-8.onrender.com/trainers/letsGoh

///
///Lesson 3
///

// LOCALHOST
### Get all contacts
GET http://localhost:8080/trainers

### Get contact by username
GET http://localhost:8080/trainers/AKetchum

### Create trainer
POST http://localhost:8080/trainers HTTP/1.1
content-type: application/json
{
    "username":"D@wn10",
    "password":"c00rdin@tor",
    "displayName":"Dawn",
    "email": "dawn10@pokemon.com",
    "info": {
        "region": "Sinnoh",
        "pokemon": "Piplup",
        "type": "Water"
    }
}

### PUT trainer
PUT http://localhost:8080/contacts/6453de61560c75d5af8daa7d HTTP/1.1
content-type: application/json
{
    "username":"letsGoh",
    "password":"futur3re@lity",
    "displayName":"Goh",
    "email": "letsGoh@pokemon.com",
    "info": {
        "region": "Kanto",
        "pokemon": "Scorbunny",
        "type": "Fire"
    }
}

### DELETE trainer
DELETE http://localhost:8080/contacts/D@wn10 HTTP/1.1

// PRODUCTION Deploy
### Get all trainers
GET https://week5-8.onrender.com/trainers


### Get trainer by username
GET https://week5-8.onrender.com/trainers/letsGoh


### Create trainer
POST https://week5-8.onrender.com/traienrs HTTP/1.1
content-type: application/json
{
    "username":"D@wn10",
    "password":"c00rdin@tor",
    "displayName":"Dawn",
    "email": "dawn10@pokemon.com",
    "info": {
        "region": "Sinnoh",
        "pokemon": "Piplup",
        "type": "Water"
    }
}

### PUT trainer
PUT https://week5-8.onrender.com/trainers/letsGoh HTTP/1.1
content-type: application/json
    {
        "username":"letsGoh",
        "password":"futur3re@lity",
        "displayName":"Goh",
        "email": "letsGoh@pokemon.com",
        "info": {
            "region": "Kanto",
            "pokemon": "Scorbunny",
            "type": "Fire"
        }
    }

### DELETE trainer
DELETE https://week5-8.onrender.com/trainer/D@wn10 HTTP/1.1